backend:
  name: git-gateway
  branch: main
# publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "/_astro"

collections:
  - name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "src/content/post"
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "image", label: "Image", widget: "image", required: false }
      - { name: "canonical", label: "Canonical", required: false }
      - { name: "publishDate", label": "Publish Date", widget: "datetime", required: false }
      - { name: "draft", label: "Is Draft?", widget: "boolean", required: false, default: false }
      - { name: "excerpt", label: "Excerpt", required: false }
      - { name: "category", label: "Category", required: false }
      - { name: "tags", label: "Tags", widget: "list", default: [], required: false }
      - { name: "author", label: "Author", required: false }
      - { label: "Content", name: "body", widget: "markdown", required: false }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/page/home.yaml"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string, required: false }
          - label: 'Widgets'
            name: 'widgets'
            widget: 'list'
            types:
              - name: 'features'
                label: 'Features'
                widget: object
                fields:
                  - { label: Title, name: title, widget: string, default: 'Title placeholder' }
                  - { label: Subtitle, name: subtitle, widget: text, default: 'Subtitle placeholder', required: false }
                  - { label: Highlight, name: highlight, widget: string, required: false }
                  - label: Items
                    name: items
                    widget: list
                    fields:
                      - {label: Title, name: title, widget: string, required: false }
                      - {label: Description, name: description, widget: markdown, required: false }
                      - {label: Icon, name: icon, widget: string, required: false }
              - name: 'features2'
                label: 'Features 2'
                widget: object
                fields:
                  - { label: Title, name: title, widget: string, default: 'Title placeholder' }
                  - { label: Subtitle, name: subtitle, widget: text, default: 'Subtitle placeholder', required: false }
                  - { label: Highlight, name: highlight, widget: string, required: false }
                  - label: Items
                    name: items
                    widget: list
                    fields:
                      - {label: Title, name: title, widget: string, required: false }
                      - {label: Description, name: description, widget: markdown, required: false }
                      - {label: Icon, name: icon, widget: string, required: false }
              - name: 'faqs'
                label: 'FAQs'
                widget: object
                fields:
                  - { label: Title, name: title, widget: string, default: 'Title placeholder' }
                  - { label: Subtitle, name: subtitle, widget: text, default: 'Subtitle placeholder', required: false }
                  - { label: Highlight, name: highlight, widget: string, required: false }
                  - label: Items
                    name: items
                    widget: list
                    fields:
                      - {label: Question, name: question, widget: string, default: "Question 1"}
                      - {label: Answer, name: answer, widget: markdown, default: "Answer 1"}